"""Ajout premiere version des tables

Revision ID: 1296d5435a79
Revises: 
Create Date: 2025-06-10 14:34:15.272532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1296d5435a79'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hommepolitique',
    sa.Column('hopol_id', sa.String(), nullable=False),
    sa.Column('role_actuel', sa.String(), nullable=True),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('profession', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('hopol_id')
    )
    op.create_table('organe',
    sa.Column('organe_id', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('code_type', sa.String(), nullable=True),
    sa.Column('debut', sa.Date(), nullable=True),
    sa.Column('fin', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('organe_id')
    )
    op.create_table('activite',
    sa.Column('activite_id', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('hopol_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hopol_id'], ['hommepolitique.hopol_id'], ),
    sa.PrimaryKeyConstraint('activite_id')
    )
    op.create_table('organe_relation',
    sa.Column('organe_id', sa.String(), nullable=False),
    sa.Column('hopol_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['hopol_id'], ['hommepolitique.hopol_id'], ),
    sa.ForeignKeyConstraint(['organe_id'], ['organe.organe_id'], ),
    sa.PrimaryKeyConstraint('organe_id', 'hopol_id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hopol_id', sa.String(), nullable=True),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.Column('date_election', sa.Date(), nullable=True),
    sa.Column('id_election', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hopol_id'], ['hommepolitique.hopol_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role')
    op.drop_table('organe_relation')
    op.drop_table('activite')
    op.drop_table('organe')
    op.drop_table('hommepolitique')
    # ### end Alembic commands ###
