"""Retire le roleactuel

Revision ID: 1cfbc4fb973a
Revises: 2ca9835f94d9
Create Date: 2025-06-12 14:26:10.060456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cfbc4fb973a'
down_revision: Union[str, None] = '2ca9835f94d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hommepolitique', 'role_actuel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hommepolitique', sa.Column('role_actuel', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
