"""Debug Type->type_declaration

Revision ID: 26309338461c
Revises: 9b6c46c30f2f
Create Date: 2025-06-18 14:18:46.509483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26309338461c'
down_revision: Union[str, None] = '9b6c46c30f2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('declaration_moneitaire', sa.Column('type_declaration', sa.String(), nullable=True, comment="Quel type de declaration est ce que c'est : declaration d'interet ou declaration de patrimoine ect"))
    op.drop_column('declaration_moneitaire', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('declaration_moneitaire', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True, comment="Quel type de declaration est ce que c'est : declaration d'interet ou declaration de patrimoine ect"))
    op.drop_column('declaration_moneitaire', 'type_declaration')
    # ### end Alembic commands ###
