"""Fusion de role et partie dans la table organe

Revision ID: 2ca9835f94d9
Revises: 9eaea2bc459a
Create Date: 2025-06-12 13:48:07.031963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ca9835f94d9'
down_revision: Union[str, None] = '9eaea2bc459a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role')
    op.drop_table('appartenanceparti')
    op.drop_table('partipolitique')
    op.add_column('organe_relation', sa.Column('access_id', sa.String(), nullable=True, comment="Une clef vers l'information d'acces au poste dans une base mongoDB"))
    op.add_column('organe_relation', sa.Column('access_type', sa.String(), nullable=True, comment='De quel facon il a acceder a cette organe'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organe_relation', 'access_type')
    op.drop_column('organe_relation', 'access_id')
    op.create_table('partipolitique',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nom', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_creation', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='partipolitique_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('appartenanceparti',
    sa.Column('hopol_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('partie_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_appartenance', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('date_quitte', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hopol_id'], ['hommepolitique.hopol_id'], name=op.f('appartenanceparti_hopol_id_fkey')),
    sa.ForeignKeyConstraint(['partie_id'], ['partipolitique.id'], name=op.f('appartenanceparti_partie_id_fkey')),
    sa.PrimaryKeyConstraint('hopol_id', 'partie_id', name=op.f('appartenanceparti_pkey'))
    )
    op.create_table('role',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hopol_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_election', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('id_election', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hopol_id'], ['hommepolitique.hopol_id'], name=op.f('role_hopol_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('role_pkey'))
    )
    # ### end Alembic commands ###
