"""Relation n-n pour les activité

Revision ID: 4502bce8af8d
Revises: a353e0499802
Create Date: 2025-06-11 15:08:50.635067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4502bce8af8d'
down_revision: Union[str, None] = 'a353e0499802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activite_hopol_association',
    sa.Column('hopol_id', sa.String(), nullable=True),
    sa.Column('activite_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['activite_id'], ['activite.activite_id'], ),
    sa.ForeignKeyConstraint(['hopol_id'], ['hommepolitique.hopol_id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activite_hopol_association')
    # ### end Alembic commands ###
