"""Debugging

Revision ID: 5ef646ada104
Revises: 59eaf99153cf
Create Date: 2025-06-12 14:41:48.450086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef646ada104'
down_revision: Union[str, None] = '59eaf99153cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activite_hopol_association', 'hopol_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('activite_hopol_association', 'activite_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activite_hopol_association', 'activite_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('activite_hopol_association', 'hopol_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
