"""Version2 de la table vote

Revision ID: 6e5fa93f3233
Revises: 783926a494ae
Create Date: 2025-06-17 11:53:18.810318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5fa93f3233'
down_revision: Union[str, None] = '783926a494ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('resultat', sa.String(), nullable=True, comment='Est ce que le vote est passer ou pas. Adopté ou Non-Adopté'))
    op.add_column('vote', sa.Column('nombre_votant', sa.Integer(), nullable=True))
    op.add_column('vote', sa.Column('suffrage_exprime', sa.Integer(), nullable=True))
    op.add_column('vote', sa.Column('vote_requis', sa.Integer(), nullable=True))
    op.add_column('vote', sa.Column('type_vote', sa.String(), nullable=True, comment="Le type de vote . Pour l'instant peut etre : scrutin public ordinaire, scrutin public solennel ou motion de censure"))
    op.add_column('vote', sa.Column('organe_votant', sa.String(), nullable=True))
    op.create_foreign_key(None, 'vote', 'organe', ['organe_votant'], ['organe_id'])
    op.drop_column('vote', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vote', type_='foreignkey')
    op.drop_column('vote', 'organe_votant')
    op.drop_column('vote', 'type_vote')
    op.drop_column('vote', 'vote_requis')
    op.drop_column('vote', 'suffrage_exprime')
    op.drop_column('vote', 'nombre_votant')
    op.drop_column('vote', 'resultat')
    # ### end Alembic commands ###
