"""Ajout qualite

Revision ID: 7018c222f7f6
Revises: 5ef646ada104
Create Date: 2025-06-12 15:02:58.377784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7018c222f7f6'
down_revision: Union[str, None] = '5ef646ada104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organe_relation', sa.Column('qualite', sa.String(), nullable=True, comment="En quel qualité il appartient a l'organisation (membres,président ect)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organe_relation', 'qualite')
    # ### end Alembic commands ###
