"""Retirer access

Revision ID: 70bd9d441567
Revises: 26309338461c
Create Date: 2025-06-18 15:05:05.347756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70bd9d441567'
down_revision: Union[str, None] = '26309338461c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('declaration_moneitaire', 'status',
               existing_type=sa.VARCHAR(),
               comment="Quel est le status de l'information. Est ce que l'information est :accessible, déposé et bientot publié,en cours,pas envoye,accessible en prefecture",
               existing_comment="Quel est le status de l'information. Est ce que l'information est : Non envoyé(homme politique illegalité),en attente,en cours de traitement,publié",
               existing_nullable=True)
    op.drop_column('declaration_moneitaire', 'access')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('declaration_moneitaire', sa.Column('access', sa.VARCHAR(), autoincrement=False, nullable=True, comment="Ou est ce que l'information sera ou est disponible:en ligne ou préfecture ou non accessible(pour certains homme politique)"))
    op.alter_column('declaration_moneitaire', 'status',
               existing_type=sa.VARCHAR(),
               comment="Quel est le status de l'information. Est ce que l'information est : Non envoyé(homme politique illegalité),en attente,en cours de traitement,publié",
               existing_comment="Quel est le status de l'information. Est ce que l'information est :accessible, déposé et bientot publié,en cours,pas envoye,accessible en prefecture",
               existing_nullable=True)
    # ### end Alembic commands ###
