"""Transformation Activite en Vote

Revision ID: 783926a494ae
Revises: 121c3388d29e
Create Date: 2025-06-17 11:12:27.701672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '783926a494ae'
down_revision: Union[str, None] = '121c3388d29e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('vote_id', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('vote_id')
    )
    op.create_table('vote_relation',
    sa.Column('hopol_id', sa.String(), nullable=False),
    sa.Column('vote_id', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=True, comment="Est ce qu'il s'agit d'un vote pour , contre , nonvotant ou abstention "),
    sa.Column('groupe_parlementaire', sa.String(), nullable=True, comment='Sous quel groupe parlementaire'),
    sa.ForeignKeyConstraint(['groupe_parlementaire'], ['organe.organe_id'], ),
    sa.ForeignKeyConstraint(['hopol_id'], ['hommepolitique.hopol_id'], ),
    sa.ForeignKeyConstraint(['vote_id'], ['vote.vote_id'], ),
    sa.PrimaryKeyConstraint('hopol_id', 'vote_id')
    )
    op.drop_table('activite_hopol_association')
    op.drop_table('activite')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activite',
    sa.Column('activite_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nom', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('activite_id', name='activite_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('activite_hopol_association',
    sa.Column('hopol_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('activite_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activite_id'], ['activite.activite_id'], name=op.f('activite_hopol_association_activite_id_fkey')),
    sa.ForeignKeyConstraint(['hopol_id'], ['hommepolitique.hopol_id'], name=op.f('activite_hopol_association_hopol_id_fkey'))
    )
    op.drop_table('vote_relation')
    op.drop_table('vote')
    # ### end Alembic commands ###
