"""Ajout de la table des declaration financiere

Revision ID: 9b6c46c30f2f
Revises: 6e5fa93f3233
Create Date: 2025-06-18 14:04:40.029298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b6c46c30f2f'
down_revision: Union[str, None] = '6e5fa93f3233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('declaration_moneitaire',
    sa.Column('decl_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hopol_id', sa.String(), nullable=True),
    sa.Column('date_traitement', sa.Date(), nullable=True, comment='a quel date a t on fait le traitement'),
    sa.Column('type', sa.String(), nullable=True, comment="Quel type de declaration est ce que c'est : declaration d'interet ou declaration de patrimoine ect"),
    sa.Column('status', sa.String(), nullable=True, comment="Quel est le status de l'information. Est ce que l'information est : Non envoyé(homme politique illegalité),en attente,en cours de traitement,publié"),
    sa.Column('access', sa.String(), nullable=True, comment="Ou est ce que l'information sera ou est disponible:en ligne ou préfecture ou non accessible(pour certains homme politique)"),
    sa.Column('id_mongo', sa.String(), nullable=True, comment="L'identifiant dans la base de donnée mongo pour l'information en brut"),
    sa.ForeignKeyConstraint(['hopol_id'], ['hommepolitique.hopol_id'], ),
    sa.PrimaryKeyConstraint('decl_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('declaration_moneitaire')
    # ### end Alembic commands ###
