"""Drop foreign key inutile

Revision ID: 9eaea2bc459a
Revises: 4502bce8af8d
Create Date: 2025-06-12 11:45:35.651673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eaea2bc459a'
down_revision: Union[str, None] = '4502bce8af8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('activite_hopol_id_fkey'), 'activite', type_='foreignkey')
    op.drop_column('activite', 'hopol_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activite', sa.Column('hopol_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('activite_hopol_id_fkey'), 'activite', 'hommepolitique', ['hopol_id'], ['hopol_id'])
    # ### end Alembic commands ###
