"""Ajout categorie proffession

Revision ID: e4308996f903
Revises: 1296d5435a79
Create Date: 2025-06-10 16:12:28.698001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4308996f903'
down_revision: Union[str, None] = '1296d5435a79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hommepolitique', sa.Column('profession_cat', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hommepolitique', 'profession_cat')
    # ### end Alembic commands ###
